version: '3.8'

services:
  telegram_bot:
    build: ./bot
    command: flask run --host=0.0.0.0 --port=5000 --reload
    ports:
      - "5000:5000"
    volumes:
      - ./bot/app:/app
    env_file:
      - ./bot/.env.dev

  card_monitor:
    build: ./services/card_monitor_app
    command: flask run --host=0.0.0.0 --port=5000 --reload
    ports:
      - "5001:5000"
    volumes:
      - ./services/card_monitor_app:/app
    env_file:
      - ./services/card_monitor_app/.env.dev
