services:
  app:
    build: .
    ports:
      - "${APP_PORT}:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=${FLASK_ENV}
    command: flask run --host=0.0.0.0 --port=5000 --reload
